apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerapp
spec:
  selector:
    matchLabels:
      app: dockerapp
  template:
    metadata:
      labels:
        app: dockerapp
    spec:
      containers:
      - name: dockerapp
        image: be4929/docker
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
------

apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: dockerapp
  ports:
  - port: 80
    targetPort: 3000
